# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-16 12:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobs_company'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobs',
            new_name='CompanyName',
        ),
    ]
