# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-16 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20180216_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='category',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
