# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-02-16 13:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='updated',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2018, 2, 16, 13, 50, 8, 350878, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
