# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-17 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_auto_20180216_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='career',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='deadLine',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='interviewExp',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='jobDescription',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='jobRequirements',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='jobinfo',
            name='videoLink',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
