# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-02-17 16:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20180217_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobinfo',
            name='logo',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
